### ISSUE TITLE
router not work as expected

### ISSUE THREAD

**Issue by sundy-li** [beego/mux#5]
I add some test code in the test file  https://github.com/beego/mux/blob/master/mux_test.go#L21

	t.Run("router with wildcard pattern2", func(t *testing.T) {
		assert := assert.New(t)

		mux := New()

		mux.Get("/a/:a/b", func(w http.ResponseWriter, r *http.Request) {
			params := Params(r)
			w.WriteHeader(200)
			w.Write([]byte(params[":a"]))
		})
		mux.Get("/a/:a/b/:b", func(w http.ResponseWriter, r *http.Request) {
			params := Params(r)
			w.WriteHeader(200)
			w.Write([]byte(params[":a"]))
		})
		mux.Get("/a/:a/b/:b/c", func(w http.ResponseWriter, r *http.Request) {
			params := Params(r)
			w.WriteHeader(200)
			w.Write([]byte(params[":a"]))
		})

		ts := httptest.NewServer(mux)
		defer ts.Close()

		res, err := Request("GET", ts.URL+"/a/a1/b/b1/c", nil)
		assert.Nil(err)
		assert.Equal(200, res.StatusCode)
		body, _ := ioutil.ReadAll(res.Body)
		assert.Equal("a1", string(body))
		res.Body.Close()
	})

1 .It didn't pass the test,   "/a/a1/b/b1/c"  not match pattern "/a/:a/b/:b/c"
2. I change the route order,  let pattern "/a/:a/b/:b/c" to be first defined router, and it matches, but 
  "/a/a1/b/b1"  not match pattern "/a/:a/b/:b"

It just passes ok in  [httprouter](https://github.com/julienschmidt/httprouter) , is that a bug of mux?

**Comment by sundy-li** [comment]
my code is update to the latest, this bug has been fixed

**Comment by astaxie** [comment]
@sundy-li thanks for the update
